### ISSUE TITLE
pip install errors

### ISSUE THREAD

**Issue by btrem** [microformats/microformats-parser-website-python#7]
I get errors running pip install:

> ERROR: Cannot install -r requirements.txt (line 12) and html5lib==0.999999999 because these package versions have conflicting dependencies.
>
> The conflict is caused by:
>     The user requested html5lib==0.999999999
>     mf2py 1.1.2 depends on html5lib>=1.0.1

> ERROR: Cannot install -r requirements.txt (line 12) and requests==2.16.4 because these package versions have conflicting dependencies.
>
> The conflict is caused by:
>    The user requested requests==2.16.4
>    mf2py 1.1.2 depends on requests>=2.18.4

I resolved the errors by changing `requirements.txt` but I don't want to create a pr until I get things working and can be at least somewhat sure that my changes are sane.

**Comment by snarfed** [comment]
Try again now that #5 is merged?

**Comment by btrem** [comment]
Yes, the problem was running python 3.1 with code that was expecting 2.7.
